config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'principal/' => 'welcome#index', as: :welcome

  get 'peliculas/'        => 'movies#index', as: :movies
  get 'peliculas/generos' => 'movies#order', as: :movie_genres
  get 'peliculas/:id'     => 'movies#show',  as: :movie
  get 'peliculas/:id/play'    => 'movies#play',    as: :movie_play
  get 'peliculas/:id/trailer' => 'movies#trailer', as: :movie_trailer
  get 'peliculas/:id/comprar' => 'movies#buy', as: :movie_buy
  post 'peliculas/comprar' => 'user#buy', as: :user_buy

  get 'series/'    => 'series#index', as: :series
  get 'series/:id' => 'series#show',  as: :serie
  get 'series/:id/trailer' => 'series#trailer', as: :serie_trailer
  post 'series/pagar' => 'series#pay', as: :serie_pay

  get 'temporadas/'    => 'seasons#index', as: :seasons
  get 'temporadas/:id' => 'seasons#show',  as: :season
  get 'temporadas/:id/play'    => 'seasons#play',    as: :season_play
  get 'temporadas/:id/trailer' => 'seasons#trailer', as: :season_trailer
  post 'temporadas/pagar' => 'seasons#pay', as: :season_pay

  get 'capitulos/'    => 'chapters#index', as: :chapters
  get 'capitulos/:id' => 'chapters#show',  as: :chapter
  get 'capitulos/:id/play'    => 'chapters#play',    as: :chapter_play
  get 'capitulos/:id/trailer' => 'chapters#trailer', as: :chapter_trailer
  post 'capitulos/pagar' => 'chapters#pay', as: :chapter_pay

  get 'perfil/' => 'user#show', as: :profile

  get 'busqueda' => 'movies#search', as: :movie_search

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base

  belongs_to :season

  def self.search(search)
    where("lower(title) LIKE ? or lower(synopsis) LIKE ? or lower(genre) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase)
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base

	has_and_belongs_to_many :users

	def self.search(search)
	  where("lower(title) LIKE ? or lower(synopsis) LIKE ? or lower(genre) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase)
	end
	
end

app/models/season.rb
class Season < ActiveRecord::Base

  belongs_to :serie
  has_many :chapters

  def self.search(search)
    where("lower(title) LIKE ? or lower(synopsis) LIKE ? or lower(genre) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase)
  end

end

app/models/serie.rb
class Serie < ActiveRecord::Base

  has_many :seasons

  def self.search(search)
    where("lower(title) LIKE ? or lower(synopsis) LIKE ? or lower(genre) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :movies
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def initialize
      super
      @user = User.find_by_username('ale')
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def play
  end

  def trailer
    @chapter = Chapter.find(params[:id])
  end

  def search
    @search_text = params[:busqueda]
    @chapters = Chapter.search(@search_text)
  end

  def pay
    @user.qpoints -= params[:qpoints].to_i
    @user.save!
    redirect_to :back
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def play
    @movie = Movie.find(params[:id])
  end

  def trailer
    @movie = Movie.find(params[:id])
  end

  def search
    @search_text = params[:busqueda]
    @movies = Movie.search(@search_text)
  end

  def order
    @movies = Movie.all
    @genres = @movies.map { |movie| movie.genre }.to_set
  end

  def buy
    @user = User.find(1)
    @movie = Movie.find(params[:id])
    if !@user.movies.include?(@movie)
      @user.qpoints -= @movie.price
      @user.movies << @movie
      @user.save!
    end
    redirect_to :back
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @seasons = Season.all
  end

  def show
    @season = Season.find(params[:id])
    @chapters = @season.chapters
  end

  def play
  end

  def trailer
    @season = Season.find(params[:id])
  end

  def search
    @search_text = params[:busqueda]
    @seasons = Season.search(@search_text)
  end

  def pay
    @user.qpoints -= params[:qpoints].to_i
    @user.save!
    redirect_to :back
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def show
    @serie = Serie.find(params[:id])
    @seasons = @serie.seasons
  end

  def play
  end

  def trailer
    @serie = Serie.find(params[:id])
  end

  def search
    @search_text = params[:busqueda]
    @series = Serie.search(@search_text)
  end

  def pay
    @user.qpoints -= params[:qpoints].to_i
    @user.save!
    redirect_to :back
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(1)
  end

  def buy
    @user.qpoints += params[:qpoints].to_i
    @user.save!
    redirect_to :back
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @movies = Movie.limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chapters/_chapter.html.erb
<div class="col-md-3 col-xs-6">
  <div class="chapter chapter-<%= chapter.id %>">
    <a href="<%= chapter_path(chapter.id) %>">
      <img class="img-responsive" src="/uploads/<%= chapter.poster %>" alt="">
    </a>
    <div class="caption">
      <h4><%= link_to chapter.title, serie_path(chapter.id) %></h4>
      <div class="stars">
        <% (1..chapter.stars).each do |i| %>
            <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
        <% (1..(5 - chapter.stars) ).each do |i| %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <span><%= chapter.genre %></span>
    </div>
  </div>
</div>

app/views/chapters/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Capítulos Disponibles</h1>
		</div>

		<% @chapters.each do |chapter| %>
        <%= render partial: "chapter", object: chapter %>
		<% end %>

	</div>
</div>

app/views/chapters/play.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/93CtmPhJgFo" frameborder="0" allowfullscreen></iframe>
</div>

app/views/chapters/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<% if @chapter.blank? %>
				<h1 class="page-header">No se encontraron resultados de búsqueda para: <%= @search_text %></h1>
			<% else %>
				<h1 class="page-header">Resultados de búsqueda para: <%= @search_text %></h1>
			<% end %>
		</div>

		<% @chapters.each do |chapter| %>
		    <%= render partial: "chapter", object: chapter %>
		<% end %>
		
	</div>
</div>

app/views/chapters/show.html.erb
<div class="container">
	<div class="row">
		<div class="serie-detail">
			<div class="col-md-12">
				<h1 class="page-header"><%= @chapter.title %></h1>
			</div>
			<div class="col-sm-3">
				<img class="img-responsive" src="/uploads/<%= @chapter.poster %>" alt="">
				<div class="stars">
					<% (1..@chapter.stars).each do |i| %>
						<i class="fa fa-star" aria-hidden="true"></i>
					<% end %>
					<% (1..(5 - @chapter.stars) ).each do |i| %>
						<i class="fa fa-star-o" aria-hidden="true"></i>
					<% end %>
				</div>
			</div>
			<div class="col-sm-8">
				<ul>
					<li>
						<strong>Titulo:</strong> <%= @chapter.title %>
					</li>
          <li>
            <strong>Capítulo:</strong> <%= @chapter.chapterNumber %>
          </li>
					<li>
						<strong>Sinopsis:</strong> <%= @chapter.synopsis %>
					</li>
					<li>
						<strong>Precio:</strong> <%= @chapter.price %>
					</li>
					<li>
						<a class="btn btn-default" href="<%= chapter_play_path(@chapter.id) %>" role="button">Ver Capítulo</a>
            <%= form_tag(chapter_pay_path, method: "post", class: "navbar-form navbar-right") do %>
                <input type="hidden" name="qpoints" value=<%= @chapter.price %>>
                <button type="submit" id="buy-button" class="btn btn-primary">
                  Pagar Capítulo: <%= @chapter.price %> QP
                </button>
            <% end %>
					</li>
          <li>
            <a class="btn btn-default" href="<%= chapter_trailer_path(@chapter.id) %>" role="button">Ver Trailer</a>
          </li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/chapters/trailer.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @chapter.url_trailer %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Qflix</title>
		<%= favicon_link_tag %>
		<%= stylesheet_link_tag 'bootstrap', 'styles', media: 'all', 'data-turbolinks-track' => true %>
		<link rel="stylesheet" type="text/css" href="/stylesheets/font-awesome.css">
		<%= javascript_include_tag 'application', 'bootstrap', 'default', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="page">
			<header>
				<nav class="navbar navbar-inverse navbar-static-top">
					<div class="container-fluid">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand" href="/">
								<img alt="Brand" src="/images/logo.png">
							</a>

						</div>
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<form class="navbar-form navbar-left" role="search" method="GET" action="busqueda">
								<div class="form-group">
									<input type="text" class="form-control" id="search-input" name="busqueda" placeholder="Buscar por título, sinopsis o género...">
								</div>
								<button type="submit" id="search-button" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i></button>
							</form>
							<ul class="nav navbar-nav navbar-right">
								<li>
									<a style='color:white' id="perfil" href="<%= profile_path %>">
                    <%= @user.username %> (<%= @user.qpoints %> QP)
                  </a>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</header>

			<%= yield %>

			<footer class="footer">
				<div class="container">
					<p class="text-muted">Sitio desarrollado por Alan Matkorski, Alejandro Rossi, Nahuel Benítez, Nicolás Pintos, Noel Zapatero y Leandro Di Lorenzo</p>
				</div>
			</footer>
		</div>
	</body>
</html>

app/views/movies/_movie.html.erb
<div class="col-md-3 col-xs-6">
  <div class="movie movie-<%= movie.id %>">
    <a href="<%= movie_path(movie.id) %>">
      <img class="img-responsive" src="/uploads/<%= movie.poster %>" alt="">
    </a>
    <div class="caption">
      <h4><%= link_to movie.title, movie_path(movie.id) %></h4>
      <div class="stars">
        <% (1..movie.stars).each do |i| %>
            <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
        <% (1..(5 - movie.stars) ).each do |i| %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <span><%= movie.genre %></span>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Películas Disponibles <a href="<%= movie_genres_url %>" class="btn btn-default pull-right">Agrupar por Género</a></h1>
		</div>

		<% @movies.each do |movie| %>
        <%= render partial: "movie", object: movie %>
		<% end %>

	</div>
</div>

app/views/movies/order.html.erb
<div class="container">
  <div class="row">
    <% @genres.each do |genre| %>
        <h1 class="page-header">Películas de <%= genre %></h1>

          <div class="row">
            <% @movies.select { |movie| movie.genre == genre }.each do |movie| %>
                <%= render partial: "movie", object: movie %>
            <% end %>
          </div>

    <% end %>
  </div>
</div>

app/views/movies/play.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @movie.url_movie %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/movies/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<% if @movies.blank? %>
				<h1 class="page-header">No se encontraron resultados de búsqueda para: <%= @search_text %></h1>
			<% else %>
				<h1 class="page-header">Resultados de búsqueda para: <%= @search_text %></h1>
			<% end %>
		</div>

		<% @movies.each do |movie| %>
		    <%= render partial: "movie", object: movie %>
		<% end %>
		
	</div>
</div>

app/views/movies/show.html.erb
<div class="container">
	<div class="row">
		<div class="movie-detail">
			<div class="col-md-12">
				<h1 class="page-header"><%= @movie.title %></h1>
			</div>
			<div class="col-sm-3">
				<img class="img-responsive" src="/uploads/<%= @movie.poster %>" alt="">
				<div class="stars">
					<% (1..@movie.stars).each do |i| %>
						<i class="fa fa-star" aria-hidden="true"></i>
					<% end %>
					<% (1..(5 - @movie.stars) ).each do |i| %>
						<i class="fa fa-star-o" aria-hidden="true"></i>
					<% end %>
				</div>
			</div>
			<div class="col-sm-8">
				<ul>
					<li>
						<strong>Año:</strong> <%= @movie.year %>
					</li>
					<li>
						<strong>Sinopsis:</strong> <%= @movie.synopsis %>
					</li>
					<li>
						<strong>Género:</strong> <%= @movie.genre %>
					</li>
					<li>
						<strong>Precio:</strong> <%= @movie.price %>
					</li>
					<li>
						<a class="btn btn-default" href="<%= movie_trailer_path(@movie.id) %>" role="button">Ver Trailer</a>
					</li>
          <li>
					<% if !@user.movies.include?(@movie) %>
							<a class="btn btn-primary" href="<%= movie_buy_path(@movie.id) %>" role="button">
                Comprar película (<%= @movie.price %> QP)
              </a>
          <% else %>
                <a class="btn btn-default" href="<%= movie_play_path(@movie.id) %>" role="button">
                  Ver Película
                </a>
					<% end %>
          </li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/movies/trailer.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @movie.url_trailer %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/seasons/_season.html.erb
<div class="col-md-3 col-xs-6">
  <div class="season season-<%= season.id %>">
    <a href="<%= season_path(season.id) %>">
      <img class="img-responsive" src="/uploads/<%= season.poster %>" alt="">
    </a>
    <div class="caption">
      <h4><%= link_to season.title, season_path(season.id) %></h4>
      <div class="stars">
        <% (1..season.stars).each do |i| %>
            <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
        <% (1..(5 - season.stars) ).each do |i| %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <span><%= season.genre %></span>
    </div>
  </div>
</div>

app/views/seasons/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Series Disponibles</h1>
		</div>

		<% @series.each do |serie| %>
        <%= render partial: "season", object: serie %>
		<% end %>

	</div>
</div>

app/views/seasons/play.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/93CtmPhJgFo" frameborder="0" allowfullscreen></iframe>
</div>

app/views/seasons/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<% if @seasons.blank? %>
				<h1 class="page-header">No se encontraron resultados de búsqueda para: <%= @search_text %></h1>
			<% else %>
				<h1 class="page-header">Resultados de búsqueda para: <%= @search_text %></h1>
			<% end %>
		</div>

		<% @seasons.each do |seasons| %>
		    <%= render partial: "season", object: season %>
		<% end %>
		
	</div>
</div>

app/views/seasons/show.html.erb
<div class="container">
	<div class="row">
		<div class="serie-detail">
			<div class="col-md-12">
				<h1 class="page-header"><%= @season.title %></h1>
			</div>
			<div class="col-sm-3">
				<img class="img-responsive" src="/uploads/<%= @season.poster %>" alt="">
				<a class="btn btn-block btn-default" href="<%= season_trailer_path(@season.id) %>">Ver Trailer</a>
				<div class="stars">
					<% (1..@season.stars).each do |i| %>
						<i class="fa fa-star" aria-hidden="true"></i>
					<% end %>
					<% (1..(5 - @season.stars) ).each do |i| %>
						<i class="fa fa-star-o" aria-hidden="true"></i>
					<% end %>
				</div>
			</div>
			<div class="col-sm-8">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Capítulos:</strong>
					</div>
					<ul class="list-group">
						<% @chapters.each do |c| %>
							<li class="list-group-item">
								<%= link_to chapter_path(c) do %>
									<%= c.chapterNumber %> - <%= c.title %>
								<%end%>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/seasons/trailer.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @season.url_trailer %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/series/_serie.html.erb
<div class="col-md-3 col-xs-6">
  <div class="serie serie-<%= serie.id %>">
    <a href="<%= serie_path(serie.id) %>">
      <img class="img-responsive" src="/uploads/<%= serie.poster %>" alt="">
    </a>
    <div class="caption">
      <h4><%= link_to serie.title, serie_path(serie.id) %></h4>
      <div class="stars">
        <% (1..serie.stars).each do |i| %>
            <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
        <% (1..(5 - serie.stars) ).each do |i| %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <span><%= serie.genre %></span>
    </div>
  </div>
</div>

app/views/series/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Series Disponibles</h1>
		</div>

		<% @series.each do |serie| %>
        <%= render partial: "serie", object: serie %>
		<% end %>

	</div>
</div>

app/views/series/play.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/93CtmPhJgFo" frameborder="0" allowfullscreen></iframe>
</div>

app/views/series/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<% if @movies.blank? %>
				<h1 class="page-header">No se encontraron resultados de búsqueda para: <%= @search_text %></h1>
			<% else %>
				<h1 class="page-header">Resultados de búsqueda para: <%= @search_text %></h1>
			<% end %>
		</div>

		<% @series.each do |serie| %>
		    <%= render partial: "serie", object: serie %>
		<% end %>
		
	</div>
</div>

app/views/series/show.html.erb
<div class="container">
	<div class="row">
		<div class="serie-detail">
			<div class="col-md-12">
				<h1 class="page-header"><%= @serie.title %></h1>
			</div>
			<div class="col-sm-3">
				<img class="img-responsive" src="/uploads/<%= @serie.poster %>" alt="">
				<div class="stars">
					<% (1..@serie.stars).each do |i| %>
						<i class="fa fa-star" aria-hidden="true"></i>
					<% end %>
					<% (1..(5 - @serie.stars) ).each do |i| %>
						<i class="fa fa-star-o" aria-hidden="true"></i>
					<% end %>
				</div>
			</div>
			<div class="col-sm-8">
				<ul>
					<li>
						<strong>Año:</strong> <%= @serie.year %>
					</li>
					<li>
						<strong>Sinopsis:</strong> <%= @serie.synopsis %>
					</li>
					<li>
						<strong>Género:</strong> <%= @serie.genre %>
					</li>
					<li>
						<strong>Precio:</strong> <%= @serie.price %>
            <%= form_tag(serie_pay_path, method: "post", class: "navbar-form navbar-right") do %>
                <input type="hidden" name="qpoints" value=<%= @serie.price %>>
                <button type="submit" id="buy-button" class="btn btn-primary">
                  Pagar Serie: <%= @serie.price %> QP
                </button>
            <% end %>
					</li>
					<li>
						<a class="btn btn-default" href="<%= serie_trailer_path(@serie.id) %>" role="button">Ver Trailer</a>
					</li>
				</ul>
			</div>
			<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-12">
					<h2 class="page-header">Seasons:</h2>
				</div>
				<% @seasons.each do |t| %>
					<div class="col-sm-2">
						<%= link_to season_path(t) do %>
							<img class="img-responsive" src="/uploads/<%= t.poster %>" alt="">
						<%end%>
					</div>
				<% end %>
			</div>
			</div>
		</div>
	</div>
</div>

app/views/series/trailer.html.erb
<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @serie.url_trailer %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header"><%= @user.username %> <small><%= @user.qpoints %> QP</small></h1>
      <h1 class="page-header">Películas adquiridas</h1>
      <% @user.movies.each do |movie| %>
        <%= render partial: "movies/movie", object: movie %>
      <% end %>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>Obtén más Qpoints!</h2>
      <%= form_tag user_buy_url, :method => "post", :class => "form-inline" %>
        <div class="form-group">
          <label class="sr-only">Email</label>
          <p class="form-control-static">Cantidad: </p>
        </div>
        <div class="form-group">
        <input type="text" class="form-control" name="qpoints" id="qpoints">
        </div>
        <button type="submit" id="buyqpoint" class="btn btn-default">Comprar QPoints</button>
      </form>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Bienvenido a Qflix!</h1>
		<p>Disfruta de QFlix, películas en streaming en tu smartTV, consola, PC, Mac, móvil, tableta y más dispositivos.</p>
		<p>
      <a class="btn btn-primary btn-lg" href="<%= movies_url %>" role="button">Películas Disponibles</a>
      <a class="btn btn-primary btn-lg" href="<%= series_url %>" role="button">Series Disponibles</a>
    </p>
	</div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Estrenos</h1>
    </div>

    <% @movies.each do |movie| %>
        <%= render partial: "movies/movie", object: movie %>
    <% end %>
  </div>
</div>